USE ClubcDb

INSERT INTO tblClubcUserClass VALUES ( '0', '관리자' )
INSERT INTO tblClubcUserClass VALUES ( '7', '나노미터' )
INSERT INTO tblClubcUserClass VALUES ( '8', '마이크로미터' )
INSERT INTO tblClubcUserClass VALUES ( '1', '매니저' )
INSERT INTO tblClubcUserClass VALUES ( '9', '밀리미터' )
INSERT INTO tblClubcUserClass VALUES ( '2', '부매니저' )
INSERT INTO tblClubcUserClass VALUES ( '10', '손님' )
INSERT INTO tblClubcUserClass VALUES ( '3', '스텝' )
INSERT INTO tblClubcUserClass VALUES ( '4', '아토미터' )
INSERT INTO tblClubcUserClass VALUES ( '5', '펨토미터' )
INSERT INTO tblClubcUserClass VALUES ( '6', '피코미터' )

INSERT INTO tblClubcUsers VALUES ( '1', '1', '손님', '손님1' )
INSERT INTO tblClubcUsers VALUES ( '10', '10', '손님', '손님10' )
INSERT INTO tblClubcUsers VALUES ( '11', '11', '손님', '손님11' )
INSERT INTO tblClubcUsers VALUES ( '12', '12', '손님', '손님12' )
INSERT INTO tblClubcUsers VALUES ( '13', '13', '손님', '손님13' )
INSERT INTO tblClubcUsers VALUES ( '14', '14', '손님', '손님14' )
INSERT INTO tblClubcUsers VALUES ( '15', '15', '손님', '손님15' )
INSERT INTO tblClubcUsers VALUES ( '16', '16', '손님', '손님16' )
INSERT INTO tblClubcUsers VALUES ( '17', '17', '손님', '손님17' )
INSERT INTO tblClubcUsers VALUES ( '18', '18', '손님', '손님18' )
INSERT INTO tblClubcUsers VALUES ( '19', '19', '손님', '손님19' )
INSERT INTO tblClubcUsers VALUES ( '2', '2', '손님', '손님2' )
INSERT INTO tblClubcUsers VALUES ( '20', '20', '손님', '손님20' )
INSERT INTO tblClubcUsers VALUES ( '3', '3', '손님', '손님3' )
INSERT INTO tblClubcUsers VALUES ( '4', '4', '손님', '손님4' )
INSERT INTO tblClubcUsers VALUES ( '40', '41', '나노미터', '말랑말랑' )
INSERT INTO tblClubcUsers VALUES ( '5', '5', '손님', '손님5' )
INSERT INTO tblClubcUsers VALUES ( '6', '6', '손님', '손님6' )
INSERT INTO tblClubcUsers VALUES ( '7', '7', '손님', '손님7' )
INSERT INTO tblClubcUsers VALUES ( '8', '8', '손님', '손님8' )
INSERT INTO tblClubcUsers VALUES ( '9', '9', '손님', '손님9' )
INSERT INTO tblClubcUsers VALUES ( '바들아메', '1', '나노미터', '바들아메' )
INSERT INTO tblClubcUsers VALUES ( '시노부', '사랑해요', '마이크로미터', '시노부' )
INSERT INTO tblClubcUsers VALUES ( 'agh1234', 'lee0926', '밀리미터', 'agh1234' )
INSERT INTO tblClubcUsers VALUES ( 'asj', '0316', '마이크로미터', 'asj' )
INSERT INTO tblClubcUsers VALUES ( 'asover', 'cangs123', '나노미터', 'Asover' )
INSERT INTO tblClubcUsers VALUES ( 'beegle20', 'commang', '마이크로미터', 'ComMang' )
INSERT INTO tblClubcUsers VALUES ( 'billgates', 'cdjsdjakstp', '피코미터', '제2의_빌게이츠' )
INSERT INTO tblClubcUsers VALUES ( 'coll21th', 'qwer1234', '마이크로미터', '쿠우' )
INSERT INTO tblClubcUsers VALUES ( 'dawbheet', 'zxcvbnm', '피코미터', 'dawbheet' )
INSERT INTO tblClubcUsers VALUES ( 'dessert5', 'dasik6', '마이크로미터', '병뚜껑' )
INSERT INTO tblClubcUsers VALUES ( 'dlarudgus20', 'qax1939', '관리자', '암겨혀' )
INSERT INTO tblClubcUsers VALUES ( 'dlwjddus4871', 'dlwjjddus1234', '마이크로미터', '이정연' )
INSERT INTO tblClubcUsers VALUES ( 'domece', 'tsw2551', '피코미터', 'Air' )
INSERT INTO tblClubcUsers VALUES ( 'gon5534', 'omg123', '마이크로미터', 'Optimus_Wu_2' )
INSERT INTO tblClubcUsers VALUES ( 'guest', 'guest', '손님', '손님' )
INSERT INTO tblClubcUsers VALUES ( 'hammerbro', 'world123', '나노미터', '폭탄펭귄' )
INSERT INTO tblClubcUsers VALUES ( 'heaven', 'Ailee', '나노미터', '감자돌이' )
INSERT INTO tblClubcUsers VALUES ( 'hun4021', '1204nuh', '마이크로미터', '엄기형' )
INSERT INTO tblClubcUsers VALUES ( 'illak', 'illaksound', '마이크로미터', 'illak' )
INSERT INTO tblClubcUsers VALUES ( 'iphone2014', '20145308', '밀리미터', '스나이퍼' )
INSERT INTO tblClubcUsers VALUES ( 'jeans01', 'jeans125', '마이크로미터', 'C언어왕이될테다' )
INSERT INTO tblClubcUsers VALUES ( 'jinsu10', '0232', '나노미터', '목적' )
INSERT INTO tblClubcUsers VALUES ( 'Jiphung', 'Jiphung98', '피코미터', '지극히_평범한_회원' )
INSERT INTO tblClubcUsers VALUES ( 'jneisa1207', 'showmethemoney', '마이크로미터', 'ㅋ' )
INSERT INTO tblClubcUsers VALUES ( 'jpk0509', '980509', '밀리미터', '공성모드' )
INSERT INTO tblClubcUsers VALUES ( 'jyossystem', 'wldhtmtltmxpa', '밀리미터', '서_포트' )
INSERT INTO tblClubcUsers VALUES ( 'KLPProgramming', 'KLP0621', '나노미터', '케빈' )
INSERT INTO tblClubcUsers VALUES ( 'Korean12', '45469', '마이크로미터', 'Korean12' )
INSERT INTO tblClubcUsers VALUES ( 'LYW', 'kkk321', '피코미터', 'LYW' )
INSERT INTO tblClubcUsers VALUES ( 'melonsoft', 'melonsoft', '나노미터', '강멜론' )
INSERT INTO tblClubcUsers VALUES ( 'mk34252', '1234', '아토미터', 'Mk' )
INSERT INTO tblClubcUsers VALUES ( 'nova0710', 'shadowspeaking', '나노미터', '안녕하세유' )
INSERT INTO tblClubcUsers VALUES ( 'nuclear1321', 'lunch1321', '나노미터', '중급자' )
INSERT INTO tblClubcUsers VALUES ( 'Nuxe', 'clcnuxe', '스텝', 'Nuxe' )
INSERT INTO tblClubcUsers VALUES ( 'PowerWinFr', '159753WinFrAUP', '나노미터', '컴퓨터_천재' )
INSERT INTO tblClubcUsers VALUES ( 'qtwyeuitoiy', 'murungdowon7', '마이크로미터', '나의꿈을향하여' )
INSERT INTO tblClubcUsers VALUES ( 'siegemode', 'cangs123', '피코미터', '시즈모드' )
INSERT INTO tblClubcUsers VALUES ( 'sizeof', 'pjy8548759', '피코미터', '하와이' )
INSERT INTO tblClubcUsers VALUES ( 'Skout', 'zmffjqTl', '매니저', '스카웃' )
INSERT INTO tblClubcUsers VALUES ( 'starbish', 'g1230a', '밀리미터', 'qorr하늘' )
INSERT INTO tblClubcUsers VALUES ( 'SYS10', 'SYS10', '마이크로미터', 'SYS10' )
INSERT INTO tblClubcUsers VALUES ( 'uier', '1324', '마이크로미터', '고구마껍질' )
INSERT INTO tblClubcUsers VALUES ( 'wookki', 'dnRl321', '마이크로미터', '우끼' )
INSERT INTO tblClubcUsers VALUES ( 'youcan1', 'ptj3124', '마이크로미터', 'youcan1' )
INSERT INTO tblClubcUsers VALUES ( 'yoyo0517', 'yoyo0517', '밀리미터', '유정' )
